AllCops:
  Exclude:
    - 'out/**/*'

Style/FileName:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassLength:
  Max: 300

Style/CyclomaticComplexity:
  Severity: warning
  Max: 10

Style/MethodLength:
  Max: 50

Style/LineLength:
  Max: 150

Style/ParameterLists:
  Max: 6
